# Generated by Django 3.1.5 on 2021-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210116_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('session_id', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=800)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('colour', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=250)),
                ('fullday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=250)),
                ('uid', models.CharField(max_length=25)),
            ],
        ),
    ]
